version: "3.9"
services:
  db:
    image: postgres:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: alpi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alpi_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./cert:/app/cert
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USERNAME: alpi
      DATABASE_PASSWORD: password
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
  node_modules:
