default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "alpi") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "alpi_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "alpi_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "alpi_production") %>
